export const SOURCES = {
  cook2014a: {
    short: "Cook et al., 2014a",
    title: "Functional movement screening: the use of fundamental movements as an assessment of function - part 1",
    type: "原始方法说明",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4060319/",
  },
  cook2014b: {
    short: "Cook et al., 2014b",
    title: "Functional movement screening: the use of fundamental movements as an assessment of function - part 2",
    type: "原始方法说明",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4127517/",
  },
  cookbook2011: {
    short: "Cook, 2011",
    title: "Movement: Functional Movement Systems. Screening-Assessment-Corrective Strategies",
    type: "专业书籍",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4060319/#B2",
  },
  bonazza2017: {
    short: "Bonazza et al., 2017",
    title: "Reliability, Validity, and Injury Predictive Value of the Functional Movement Screen",
    type: "系统综述与 Meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/27159297/",
  },
  moran2017: {
    short: "Moran et al., 2017",
    title: "Do Functional Movement Screen composite scores predict subsequent injury?",
    type: "系统综述与 Meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/28360142/",
  },
  plisky2006: {
    short: "Plisky et al., 2006",
    title: "Star Excursion Balance Test as a predictor of lower extremity injury in high school basketball players",
    type: "前瞻性队列研究",
    url: "https://pubmed.ncbi.nlm.nih.gov/17193868/",
  },
  plisky2009: {
    short: "Plisky et al., 2009",
    title: "The reliability of an instrumented device for measuring components of the Star Excursion Balance Test",
    type: "可靠性研究",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2953327/",
  },
  gribble2012: {
    short: "Gribble et al., 2012",
    title: "Using the Star Excursion Balance Test to assess dynamic postural-control deficits and outcomes",
    type: "系统综述",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3392165/",
  },
  macgregor2018: {
    short: "Macgregor et al., 2018",
    title: "Assessment of Skeletal Muscle Contractile Properties by Radial Displacement: The Case for Tensiomyography",
    type: "批判性综述",
    url: "https://pubmed.ncbi.nlm.nih.gov/29605838/",
  },
  ciel2023: {
    short: "Čular et al., 2023",
    title: "Tensiomyography: from muscle assessment to talent identification tool",
    type: "叙述性综述",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC10330706/",
  },
  tmg2025: {
    short: "Paravlic, 2025",
    title: "Establishing reference values for tensiomyography-derived parameters in soccer players",
    type: "系统综述、Meta-analysis 与 Meta-regression",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC11694203/",
  },
  hrv1996: {
    short: "ESC/NASPE Task Force, 1996",
    title: "Heart rate variability: standards of measurement, physiological interpretation and clinical use",
    type: "国际工作组标准",
    url: "https://pubmed.ncbi.nlm.nih.gov/8598068/",
  },
  bellenger2016: {
    short: "Bellenger et al., 2016",
    title: "Monitoring Athletic Training Status Through Autonomic Heart Rate Regulation",
    type: "系统综述与 Meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/26888648/",
  },
  shaffer2017: {
    short: "Shaffer & Ginsberg, 2017",
    title: "An Overview of Heart Rate Variability Metrics and Norms",
    type: "综述",
    url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5624990/",
  },
  appelbaum2018: {
    short: "Appelbaum & Erickson, 2018",
    title: "Sports vision training: A review of the state-of-the-art in digital training techniques",
    type: "同行评审综述",
    url: "https://doi.org/10.1080/1750984X.2016.1266376",
  },
  maloney2019: {
    short: "Maloney, 2019",
    title: "The Relationship Between Asymmetry and Athletic Performance: A Critical Review",
    type: "批判性综述",
    url: "https://pubmed.ncbi.nlm.nih.gov/29742749/",
  },
  prieske2016: {
    short: "Prieske et al., 2016",
    title: "The Role of Trunk Muscle Strength for Physical Fitness and Athletic Performance",
    type: "系统综述与 Meta-analysis",
    url: "https://pubmed.ncbi.nlm.nih.gov/26589515/",
  },
};

export const CATEGORIES = [
  { id: "all", label: "全部指标", short: "全部" },
  { id: "recovery", label: "基础恢复", short: "恢复" },
  { id: "vision", label: "视觉功能", short: "视觉" },
  { id: "fms", label: "FMS 筛查", short: "FMS" },
  { id: "tmg", label: "TMG 肌肉评估", short: "TMG" },
  { id: "performance", label: "运动功能", short: "运动" },
  { id: "ybt", label: "YBT / 核心", short: "YBT" },
];

const bilateralLowerChain = [
  "pelvis", "core_front", "core_back", "hip_l", "hip_r", "glute_l", "glute_r",
  "quad_l", "quad_r", "hamstring_l", "hamstring_r", "knee_l", "knee_r",
  "calf_l", "calf_r", "tibialis_l", "tibialis_r", "ankle_l", "ankle_r",
  "foot_l", "foot_r",
];

const tmgSites = [
  { id: "all", label: "常用测点", regions: ["quad_l", "quad_r", "hamstring_l", "hamstring_r", "calf_l", "calf_r"] },
  { id: "rf", label: "股直肌", regions: ["quad_l", "quad_r"] },
  { id: "bf", label: "股二头肌", regions: ["hamstring_l", "hamstring_r"] },
  { id: "gm", label: "腓肠肌", regions: ["calf_l", "calf_r"] },
  { id: "ta", label: "胫骨前肌", regions: ["tibialis_l", "tibialis_r"] },
  { id: "es", label: "竖脊肌", regions: ["core_back", "lumbar_spine"] },
];

export const INDICATORS = [
  {
    id: "hrv",
    category: "recovery",
    title: "心率变异性",
    unit: "ms",
    range: "表内范围 55-105",
    target: "表内达标值 55",
    risk: "表内危险值 <50",
    evidenceGrade: "需个体基线",
    summary: "反映连续心搏间期波动及自主神经调节。运动监测应固定体位、时段、记录长度和具体指标名称，并优先观察个人滚动基线与趋势。",
    evidence: "Excel 未说明使用 RMSSD、SDNN 或其他 HRV 指标，固定 55/50 ms 不能作为跨设备、跨年龄和跨人群的通用损伤阈值。HRV 变化也需要与训练负荷、症状、睡眠和表现共同解释。",
    primaryRegions: ["heart", "brain"],
    secondaryRegions: ["neck", "chest"],
    primaryText: "心脏节律、自主神经中枢",
    secondaryText: "颈部自主神经通路、胸廓",
    sources: ["hrv1996", "shaffer2017", "bellenger2016"],
  },
  {
    id: "simple-visual-reaction",
    category: "vision",
    title: "简单视觉反应",
    unit: "ms",
    range: "表内范围 280-380",
    target: "表内达标值 300",
    risk: "表内危险值 >360",
    evidenceGrade: "协议依赖",
    summary: "从视觉刺激出现到指定运动反应完成的总时程，包含视网膜输入、中枢加工、运动指令与执行器反应。",
    evidence: "反应时高度依赖刺激亮度、显示延迟、按键设备、优势手、熟悉度和任务规则。300/360 ms 可保留为本系统内部规则，但不应标注为通用临床标准。",
    primaryRegions: ["eyes", "brain", "forearm_l", "forearm_r", "hand_l", "hand_r"],
    secondaryRegions: ["neck", "shoulder_l", "shoulder_r"],
    primaryText: "双眼、视觉-运动中枢、反应手",
    secondaryText: "颈部与肩带稳定",
    sources: ["appelbaum2018"],
  },
  {
    id: "dynamic-vision",
    category: "vision",
    title: "动态视觉能力",
    unit: "ms",
    range: "表内范围 50-200",
    target: "表内达标值 50-100",
    risk: "表内危险值 >200",
    evidenceGrade: "定义待补全",
    summary: "用于描述运动目标追踪、动态视敏度或快速注视转换时，眼动与视觉加工的协同表现。",
    evidence: "“动态视觉能力”不是单一标准化量。必须记录采用的是动态视敏度、平滑追踪、扫视还是目标识别任务；不同任务的毫秒值不可直接互换。",
    primaryRegions: ["eyes", "brain"],
    secondaryRegions: ["neck"],
    primaryText: "双眼、视觉皮层与眼动控制",
    secondaryText: "头颈稳定与前庭-眼反射相关区域",
    sources: ["appelbaum2018"],
  },
  {
    id: "visual-decision",
    category: "vision",
    title: "视觉决策能力",
    unit: "成功点击数量",
    range: "表内范围 10-40",
    target: "表内达标值 30",
    risk: "表内危险值 10",
    evidenceGrade: "任务依赖",
    summary: "整合目标识别、选择性注意、反应抑制、决策和手部执行，属于视觉-认知-运动复合任务。",
    evidence: "点击数量必须与测试时长、目标数、假阳性、遗漏率和设备延迟一起报告。单独用 10 次无法跨任务判定功能受损。",
    primaryRegions: ["eyes", "brain", "hand_l", "hand_r"],
    secondaryRegions: ["forearm_l", "forearm_r", "shoulder_l", "shoulder_r"],
    primaryText: "双眼、额顶叶决策网络、双手",
    secondaryText: "前臂与肩带执行链",
    sources: ["appelbaum2018"],
  },
  {
    id: "fms-deep-squat",
    category: "fms",
    title: "深蹲",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "双侧对称地检查髋、膝、踝功能活动度；过顶杆同时要求双肩与胸椎活动度，并挑战核心控制。",
    evidence: "低分只说明该动作模式需要进一步检查，不能从单个分数直接诊断某一肌肉或关节病变。",
    primaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r", "shoulder_l", "shoulder_r", "thoracic_spine"],
    secondaryRegions: ["core_front", "core_back", "pelvis", "foot_l", "foot_r"],
    primaryText: "双侧髋、膝、踝、肩与胸椎",
    secondaryText: "核心、骨盆和足部控制",
    sources: ["cook2014a", "cookbook2011"],
  },
  {
    id: "fms-hurdle-step",
    category: "fms",
    title: "跨栏步",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "检查步态样动作中的单腿站立稳定、跨步腿髋膝踝活动、双侧髋活动差异以及骨盆和躯干控制。",
    evidence: "站立腿和跨步腿承担不同任务，界面同时标注双侧下肢与骨盆；实际评分仍需分别记录左右侧。",
    primaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r", "pelvis"],
    secondaryRegions: ["core_front", "core_back", "glute_l", "glute_r", "foot_l", "foot_r"],
    primaryText: "双侧髋、膝、踝与骨盆",
    secondaryText: "核心、臀肌与足部平衡",
    sources: ["cook2014a", "cookbook2011"],
  },
  {
    id: "fms-inline-lunge",
    category: "fms",
    title: "直线弓箭步",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "窄支撑面下检查髋与踝活动/稳定、膝稳定、股四头肌柔韧性以及躯干抗旋转和平衡。",
    evidence: "前后腿需求不完全相同；低分可来自髋活动受限、膝踝稳定不足、髋内收/外展控制失衡或胸椎限制。",
    primaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r", "quad_l", "quad_r"],
    secondaryRegions: ["adductor_l", "adductor_r", "glute_l", "glute_r", "core_front", "core_back", "thoracic_spine"],
    primaryText: "髋、膝、踝与股四头肌",
    secondaryText: "髋内外侧控制、核心和胸椎",
    sources: ["cook2014a", "cookbook2011"],
  },
  {
    id: "fms-shoulder-mobility",
    category: "fms",
    title: "肩部灵活性",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "组合一侧肩内旋/内收与另一侧肩外旋/外展，要求肩胛运动和胸椎伸展，并观察双侧差异。",
    evidence: "胸小肌、背阔肌、肩袖或肩胛胸廓控制可能影响表现，但 FMS 低分本身不能确定具体组织。疼痛清除试验阳性应进入进一步评估。",
    primaryRegions: ["shoulder_l", "shoulder_r", "scapula_l", "scapula_r", "thoracic_spine"],
    secondaryRegions: ["chest", "upper_arm_l", "upper_arm_r", "core_front", "core_back"],
    primaryText: "双肩、肩胛与胸椎",
    secondaryText: "胸肌/背阔肌区域、上臂与核心",
    sources: ["cook2014b", "cookbook2011"],
  },
  {
    id: "fms-aslr",
    category: "fms",
    title: "主动直腿上抬",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "检查下肢与躯干分离时的主动腘绳肌和腓肠-比目鱼肌柔韧性，同时要求对侧髋伸展及骨盆/核心稳定。",
    evidence: "髂腰肌紧张、骨盆前倾或对侧稳定不足都可能限制表现，因此界面同时标注后侧链、髋前侧与核心。",
    primaryRegions: ["hamstring_l", "hamstring_r", "calf_l", "calf_r", "hip_l", "hip_r"],
    secondaryRegions: ["pelvis", "core_front", "core_back", "lumbar_spine"],
    primaryText: "腘绳肌、腓肠肌群与髋",
    secondaryText: "骨盆、髂腰肌区域与核心",
    sources: ["cook2014b", "cookbook2011"],
  },
  {
    id: "fms-trunk-pushup",
    category: "fms",
    title: "躯干稳定俯卧撑",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "在对称上肢闭链推起时检查矢状面躯干稳定，要求身体整体抬起而腰椎不塌陷或滞后。",
    evidence: "主要解释是抗伸展核心稳定；肩、肘、腕和胸廓是完成动作的承重链，但不应把低分直接等同于腹肌无力。",
    primaryRegions: ["core_front", "core_back", "lumbar_spine", "thoracic_spine"],
    secondaryRegions: ["shoulder_l", "shoulder_r", "upper_arm_l", "upper_arm_r", "wrist_l", "wrist_r"],
    primaryText: "腹壁、背部稳定肌与脊柱",
    secondaryText: "肩、上臂与腕部承重链",
    sources: ["cook2014b", "cookbook2011"],
  },
  {
    id: "fms-rotary-stability",
    category: "fms",
    title: "旋转稳定性",
    unit: "分 (0-3)",
    range: "0-3",
    target: "3 分（标准完成）",
    risk: "0 分（疼痛）或 1 分",
    evidenceGrade: "动作定义明确",
    summary: "四点支撑下组合上肢与下肢运动，检查矢状面和横断面的非对称躯干稳定、神经肌肉协调与跨躯干力量传递。",
    evidence: "该动作是全身运动链任务，重点为躯干抗旋转，但肩胛、肩、髋和支撑肢也参与控制。",
    primaryRegions: ["core_front", "core_back", "thoracic_spine", "lumbar_spine", "pelvis"],
    secondaryRegions: ["scapula_l", "scapula_r", "shoulder_l", "shoulder_r", "hip_l", "hip_r", "glute_l", "glute_r"],
    primaryText: "多平面核心、胸腰椎与骨盆",
    secondaryText: "肩胛、肩、髋和臀部",
    sources: ["cook2014b", "cookbook2011"],
  },
  {
    id: "fms-composite",
    category: "fms",
    title: "FMS 综合评分",
    unit: "分 (0-21)",
    range: "0-21",
    target: "表内达标值 >=17",
    risk: "表内危险值 <=14",
    evidenceGrade: "预测价值有限",
    summary: "7 个动作最低侧得分的总和，用于建立总体动作基线；疼痛项记 0 分并需要进一步评估。",
    evidence: "系统综述认为 <=14 与部分人群后续损伤有小幅关联，但不足以作为个体损伤预测工具；足球等人群证据有限或相互冲突。",
    primaryRegions: ["shoulder_l", "shoulder_r", "thoracic_spine", "core_front", "core_back", "pelvis", "hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r"],
    secondaryRegions: ["scapula_l", "scapula_r", "glute_l", "glute_r", "foot_l", "foot_r"],
    primaryText: "全身关键运动链",
    secondaryText: "肩胛、臀部与足部控制",
    sources: ["bonazza2017", "moran2017", "cook2014a", "cook2014b"],
  },
  {
    id: "tmg-delay",
    category: "tmg",
    title: "反应时间 (Td)",
    unit: "ms",
    range: "表内未设范围",
    target: "表内达标值 <30",
    risk: "表内危险值 >50",
    evidenceGrade: "肌肉/协议依赖",
    summary: "从电刺激开始到肌腹径向位移达到 Dm 的 10% 所需时间，描述刺激后机械反应的延迟。",
    evidence: "Td 不是全身神经反应时。其数值受被测肌肉、个体、体位、电极和传感器放置影响，表内 30/50 ms 不宜作为所有肌肉的通用阈值。",
    primaryRegions: tmgSites[0].regions,
    secondaryRegions: ["knee_l", "knee_r", "ankle_l", "ankle_r"],
    primaryText: "当前 TMG 肌肉测点",
    secondaryText: "相关关节仅作功能链提示",
    sources: ["ciel2023", "macgregor2018", "tmg2025"],
    sites: tmgSites,
  },
  {
    id: "tmg-contraction",
    category: "tmg",
    title: "收缩时间 (Tc)",
    unit: "ms",
    range: "表内未设范围",
    target: "表内达标值 <50",
    risk: "表内危险值 >100",
    evidenceGrade: "肌肉/协议依赖",
    summary: "位移曲线上升段从 10% Dm 到 90% Dm 的时间，反映被测浅表肌肉抽搐的机械收缩速度。",
    evidence: "Tc 不是“从 10% 到 90% 最大收缩力”的时间。不同肌肉具有不同参考分布，固定 50/100 ms 不能脱离肌肉、运动项目和人群使用。",
    primaryRegions: tmgSites[0].regions,
    secondaryRegions: ["knee_l", "knee_r", "ankle_l", "ankle_r"],
    primaryText: "当前 TMG 肌肉测点",
    secondaryText: "相关关节仅作功能链提示",
    sources: ["ciel2023", "macgregor2018", "tmg2025"],
    sites: tmgSites,
  },
  {
    id: "tmg-displacement",
    category: "tmg",
    title: "最大径向位移 (Dm)",
    unit: "mm",
    range: "表内未设范围",
    target: "参考个体基线",
    risk: "表内危险值 <基线 70%",
    evidenceGrade: "肌肉/协议依赖",
    summary: "电刺激诱发等长抽搐时，传感器记录的肌腹最大径向位移；与肌肉刚度、结构和状态相关。",
    evidence: "Dm 测量的是肌腹而不是“最大肌腱位移”。低于个人基线可用于监测，但 70%/50% 需要本设备、同一肌肉和重复测量可靠性支持。",
    primaryRegions: tmgSites[0].regions,
    secondaryRegions: ["knee_l", "knee_r", "ankle_l", "ankle_r"],
    primaryText: "当前 TMG 肌肉测点",
    secondaryText: "邻近肌腱/关节不作为 Dm 直接测量对象",
    sources: ["macgregor2018", "ciel2023", "tmg2025"],
    sites: tmgSites,
  },
  {
    id: "tmg-symmetry",
    category: "tmg",
    title: "功能对称性",
    unit: "%",
    range: "表内未设范围",
    target: "表内参考 80 分",
    risk: "表内危险值 <80",
    evidenceGrade: "算法待声明",
    summary: "比较双侧同名肌或主动肌/拮抗肌的 TMG 参数，可用于发现相对差异，但结果取决于所选参数和计算公式。",
    evidence: "“功能对称性”不是单一原始 TMG 参数。网页保留 80 的内部规则，同时要求在正式系统中公开公式、肌肉配对、方向和最小可靠变化。",
    primaryRegions: ["quad_l", "quad_r", "hamstring_l", "hamstring_r", "calf_l", "calf_r"],
    secondaryRegions: ["knee_l", "knee_r", "ankle_l", "ankle_r", "pelvis"],
    primaryText: "左右同名肌与主动/拮抗肌对",
    secondaryText: "膝、踝和骨盆功能链",
    sources: ["macgregor2018", "tmg2025", "maloney2019"],
    sites: tmgSites,
  },
  {
    id: "interlimb-strength",
    category: "performance",
    title: "下肢双侧肢体力量差值",
    unit: "% 或 kg",
    range: "表内下限 0",
    target: "表内达标值 <10%",
    risk: "表内危险值 >15%",
    evidenceGrade: "测试依赖",
    summary: "比较左右下肢在等速肌力、单腿跳或测力台任务中的输出差异，重点是同一测试、同一方向和同一算法下的变化。",
    evidence: "10%/15% 是常见实践阈值而非统一生物学分界。差异大小、优势侧方向和表现/损伤关系会随任务、指标和运动项目改变。",
    primaryRegions: ["glute_l", "glute_r", "quad_l", "quad_r", "hamstring_l", "hamstring_r", "calf_l", "calf_r"],
    secondaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r"],
    primaryText: "双侧臀、股前/后侧与小腿肌群",
    secondaryText: "髋、膝、踝关节链",
    sources: ["maloney2019"],
  },
  {
    id: "ybt-composite",
    category: "ybt",
    title: "YBT 综合评分",
    unit: "%（标准化）",
    range: "(三方向距离和)/(腿长 x 3) x 100",
    target: "表内达标值 >=95%",
    risk: "表内危险值 <85%",
    evidenceGrade: "人群依赖",
    summary: "单腿站立时向前、后内和后外三个方向触及，综合反映动态姿势控制、下肢活动度、力量与本体感觉。",
    evidence: "经典前瞻性研究在女性高中篮球运动员中观察到综合分 <94% 与损伤相关，不能直接外推为所有运动员的 95/85 通用分界。",
    primaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r", "foot_l", "foot_r"],
    secondaryRegions: ["glute_l", "glute_r", "quad_l", "quad_r", "hamstring_l", "hamstring_r", "pelvis", "core_front", "core_back"],
    primaryText: "双侧髋、膝、踝与足部",
    secondaryText: "臀腿肌群、骨盆与核心",
    sources: ["plisky2006", "plisky2009", "gribble2012"],
  },
  {
    id: "ybt-symmetry",
    category: "ybt",
    title: "YBT 对称性",
    unit: "cm 或 %",
    range: "表内下限 0",
    target: "表内达标值 <4 cm",
    risk: "表内危险值 >8 cm",
    evidenceGrade: "方向需校正",
    summary: "比较左右侧同一触及方向的距离差，定位动态平衡的不对称方向。",
    evidence: "Plisky 2006 支持的是前向触及左右差 >4 cm，而 Excel 写的是后内侧。不同方向不可互换；>8 cm 也缺少通用高风险依据。正式系统必须保存方向。",
    primaryRegions: ["hip_l", "hip_r", "knee_l", "knee_r", "ankle_l", "ankle_r", "foot_l", "foot_r"],
    secondaryRegions: ["glute_l", "glute_r", "pelvis", "core_front", "core_back"],
    primaryText: "左右承重侧髋、膝、踝与足",
    secondaryText: "臀部、骨盆与核心控制",
    sources: ["plisky2006", "gribble2012"],
  },
  {
    id: "core-stability",
    category: "ybt",
    title: "核心稳定评分",
    unit: "分",
    range: "表内下限 0",
    target: "表内达标值 >=80",
    risk: "表内危险值 <60",
    evidenceGrade: "自定义复合分",
    summary: "可整合腹桥、侧桥、背桥和躯干旋转任务，但必须先规定每个子测试、权重、终止标准和常模人群。",
    evidence: "文献支持躯干肌力/耐力可训练，但与运动表现的关系通常较小，且不存在统一的 0-100 核心稳定评分。80/60 应标注为本系统内部规则。",
    primaryRegions: ["core_front", "core_back", "thoracic_spine", "lumbar_spine", "pelvis"],
    secondaryRegions: ["glute_l", "glute_r", "shoulder_l", "shoulder_r", "hip_l", "hip_r"],
    primaryText: "腹壁、斜肌、背伸肌、胸腰椎与骨盆",
    secondaryText: "臀部、肩带和髋部支撑链",
    sources: ["prieske2016", "cookbook2011"],
  },
];

export const BODY_REGION_LABELS = {
  brain: "脑与中枢加工",
  eyes: "双眼",
  heart: "心脏",
  neck: "颈部",
  chest: "胸廓",
  thoracic_spine: "胸椎",
  lumbar_spine: "腰椎",
  core_front: "前外侧核心",
  core_back: "后侧核心",
  pelvis: "骨盆",
  shoulder_l: "左肩",
  shoulder_r: "右肩",
  scapula_l: "左肩胛",
  scapula_r: "右肩胛",
  upper_arm_l: "左上臂",
  upper_arm_r: "右上臂",
  forearm_l: "左前臂",
  forearm_r: "右前臂",
  wrist_l: "左腕",
  wrist_r: "右腕",
  hand_l: "左手",
  hand_r: "右手",
  hip_l: "左髋",
  hip_r: "右髋",
  glute_l: "左臀",
  glute_r: "右臀",
  adductor_l: "左髋内收肌群",
  adductor_r: "右髋内收肌群",
  quad_l: "左股四头肌",
  quad_r: "右股四头肌",
  hamstring_l: "左腘绳肌",
  hamstring_r: "右腘绳肌",
  knee_l: "左膝",
  knee_r: "右膝",
  calf_l: "左小腿后侧",
  calf_r: "右小腿后侧",
  tibialis_l: "左胫骨前肌",
  tibialis_r: "右胫骨前肌",
  ankle_l: "左踝",
  ankle_r: "右踝",
  foot_l: "左足",
  foot_r: "右足",
};

export function getIndicator(id) {
  return INDICATORS.find((indicator) => indicator.id === id) ?? INDICATORS[0];
}

export function getIndicatorRegions(indicator, siteId = "all") {
  if (!indicator.sites) {
    return {
      primary: indicator.primaryRegions,
      secondary: indicator.secondaryRegions,
    };
  }

  const site = indicator.sites.find((item) => item.id === siteId) ?? indicator.sites[0];
  return {
    primary: site.regions,
    secondary: indicator.secondaryRegions,
  };
}
