const { chromium } = require('playwright');
const assert = require('node:assert/strict');
(async () => {
 const browser = await chromium.launch({headless:true});
 const page = await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 const errors=[]; page.on('pageerror',e=>errors.push(e.message));
 await page.goto('http://127.0.0.1:4173/references/');
 assert.equal(await page.title(),'运动损伤预防 · 解剖参考图工作台');
 await page.waitForSelector('[data-ready="true"]',{timeout:90000});
 assert.equal(await page.locator('#course option').count(),10);
 for(let i=0;i<10;i++) {
   await page.selectOption('#course',String(i));
   assert.ok(Number(await page.locator('#selected-count').textContent())>0,`course ${i} has no mesh matches`);
 }
 await page.fill('#search','股四头肌');
 assert.ok(await page.locator('#muscles input').count()>0,'Chinese search failed');
 await page.fill('#search','no-such-muscle');
 assert.equal(await page.locator('#muscles input').count(),0);
 await page.fill('#search','');
 await page.click('#clear');
 assert.equal(await page.locator('#selected-count').textContent(),'0');
 await page.selectOption('#course','4');
 await page.getByRole('button',{name:'后侧',exact:true}).click();
 await page.selectOption('#resolution','2048');
 const [download] = await Promise.all([page.waitForEvent('download'),page.getByRole('button',{name:'导出 PNG',exact:true}).click()]);
 await download.saveAs('/private/tmp/reference-test.png');
 assert.match(download.suggestedFilename(),/\.png$/);
 await page.selectOption('#course','0');
 const [license] = await Promise.all([page.waitForEvent('download'),page.click('#attribution')]);
 await license.saveAs('/private/tmp/reference-attribution.txt');
 const licenseText=require('fs').readFileSync('/private/tmp/reference-attribution.txt','utf8');
 assert.match(licenseText,/CC BY-SA/);
 assert.match(licenseText,/课程：05 膝关节功能训练/,'license must correspond to exported image rather than current selection');
 await page.selectOption('#course','4');
 await page.selectOption('#resolution','4096');
 await page.selectOption('#background','white');
 const [white] = await Promise.all([page.waitForEvent('download'),page.click('#export')]);
 await white.saveAs('/private/tmp/reference-white.png');
 await page.setViewportSize({width:390,height:844});
 await page.screenshot({path:'/private/tmp/reference-mobile.png'});
 assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),'mobile horizontal overflow');
 await page.setViewportSize({width:1440,height:1000});
 await page.screenshot({path:'/private/tmp/reference-desktop.png'});
 await page.goto('http://127.0.0.1:4173/');
 await page.waitForSelector('[data-muscle-mesh-count]',{timeout:90000});
 assert.equal(await page.locator('a[href="./references/"]').count(),1);
 assert.deepEqual(errors,[]);
 await browser.close(); console.log('PASS: 10 presets, model load, search, clear, transparent/white export, attribution, mobile layout, original atlas');
})().catch(e=>{console.error(e);process.exit(1)});
